/* =====================================================================
   Requirements Coverage inventory.
   Every requirement extracted from the 11-page PDF, its page, and the
   route that demonstrates it. Doubles as the customer sign-off matrix
   (rendered at #/coverage) and a runnable self-check (console on boot).
   ===================================================================== */

(function () {
  const App = window.App;

  // group -> [{id, page, text, route}]
  App.COVERAGE = [
    { group: 'Modules (p.1)', items: [
      { id: 'M1', page: 1, text: 'Procurement Interface: receive PR/PO, do Goods Receipt (GR) from SAP', route: '#/intake' },
      { id: 'M2', page: 1, text: 'Asset Registration: asset created by SAP / Accounting (Asset code, Cap date, Cost, buyer, PO number)', route: '#/intake' },
      { id: 'M3', page: 1, text: 'Asset Assignment: QR tag per company, photo & detail, owner/user, install location, cost center, lat/long, cap date, cost, brand, model, serial/car number, age, warranty', route: '#/scan' },
      { id: 'M4', page: 1, text: 'Asset Movement: transfer / borrow-return / repair / receive / change holder', route: '#/movement' },
      { id: 'M5', page: 1, text: 'Inventory Management: plan, assign and run annual count', route: '#/counts' },
      { id: 'M6', page: 1, text: 'Reconciliation: compare actual vs SAP, analyse variance, propose corrections', route: '#/reconcile' },
      { id: 'M7', page: 1, text: 'Disposal & Write-off: sell, donate, destroy, lost, retire with approval workflow', route: '#/writeoff' },
      { id: 'M8', page: 1, text: 'SAP Integration: connect SAP S/4HANA to receive & update automatically', route: '#/admin' },
      { id: 'M9', page: 1, text: 'Reporting & Dashboard: Asset Register, Inventory, Disposal, KPI and executive dashboard', route: '#/dashboard' },
      { id: 'M10', page: 1, text: 'Administration & Audit: user rights, audit log, system config', route: '#/admin' },
    ]},
    { group: 'Asset sources (p.2)', items: [
      { id: 'S1', page: 2, text: 'Asset from SAP: no request or registration needed in WeCGA', route: '#/assets' },
      { id: 'S2', page: 2, text: 'Found asset not in SAP, < 2,000 THB: no SAP code, create manually in WeCGA (single or Mass Data)', route: '#/registration' },
      { id: 'S3', page: 2, text: 'Found asset written off in SAP but physically still in use: re-register in WeCGA', route: '#/registration' },
    ]},
    { group: 'SAP asset intake & tagging (p.2)', items: [
      { id: 'I1', page: 2, text: 'Asset purchased via PR/PO', route: '#/intake' },
      { id: 'I2', page: 2, text: 'User confirms delivery date in advance to schedule QR tagging appointment', route: '#/intake' },
      { id: 'I3', page: 2, text: 'User records Goods Receipt (GR) in SAP', route: '#/intake' },
      { id: 'I4', page: 2, text: 'Accounting checks and creates/records the asset', route: '#/intake' },
      { id: 'I5', page: 2, text: 'Accounting notifies Asset Team of new asset to track QR tagging', route: '#/tagging' },
      { id: 'I6', page: 2, text: 'QR generated by central Asset Team only', route: '#/tagging' },
      { id: 'I7', page: 2, text: 'GA (RO) is the intermediary controlling tagging in each area', route: '#/tagging' },
      { id: 'I8', page: 2, text: 'Tag applied by GA-Asset Team (AIS 6 areas / BB 10 areas) or by local employee/user', route: '#/tagging' },
    ]},
    { group: 'First record: scan & photo (p.2-3, item 8)', items: [
      { id: 'P1', page: 2, text: '8.1 Scan QR', route: '#/scan' },
      { id: 'P2', page: 3, text: '8.2 Capture 3 photos: QR code, Serial number, whole-asset overview', route: '#/scan' },
      { id: 'P3', page: 3, text: '8.3 Photo location must match the physical asset; Location per SAP', route: '#/scan' },
      { id: 'P4', page: 3, text: '8.4 AI checks serial in photo vs record and whether photo is fake', route: '#/scan' },
      { id: 'P5', page: 3, text: '8.5 Photo carries Latitude/Longitude, address, district, province', route: '#/scan' },
      { id: 'P6', page: 3, text: 'Asset-Team first-record 8-point verification checklist (asset/QR/serial photos, description match, location, serial, owner, org)', route: '#/scan' },
    ]},
    { group: 'Handover (p.3, item 9)', items: [
      { id: 'H1', page: 3, text: 'Deliver to holder; receiver must accept in the system (traceability)', route: '#/handover' },
      { id: 'H2', page: 3, text: 'Send per-item or as a list, via Email or as a WeCGA record', route: '#/handover/new' },
      { id: 'H3', page: 3, text: 'Owner = individual (email required) or organization (Head-of email)', route: '#/handover' },
    ]},
    { group: 'WeCGA capabilities (p.3, item 10)', items: [
      { id: 'W1', page: 3, text: '10.1 Add < 2,000 THB asset, generate Asset Code separate from SAP', route: '#/registration' },
      { id: 'W2', page: 3, text: '10.2 Employee finds asset and sends request to Asset Management', route: '#/registration' },
      { id: 'W3', page: 3, text: '10.2 Transfer request between person/org; GA verifies via scan + destination photo', route: '#/movement' },
      { id: 'W4', page: 3, text: '10.3 Annual count nationwide + special RO round (independent of annual)', route: '#/counts' },
      { id: 'W5', page: 3, text: '10.4 Disposal / donation / write-off', route: '#/writeoff' },
    ]},
    { group: 'Register not-in-SAP asset (p.4)', items: [
      { id: 'R1', page: 4, text: 'Employee submits request to Asset Management', route: '#/registration' },
      { id: 'R2', page: 4, text: 'WeCGA header must match SAP header (Asset Code, Cap date, Brand, Model, Serial/car, Cost, PO, Location, Lat/Long, Owner, Email, Org, Warranty, Age, NBV from SAP)', route: '#/registration' },
      { id: 'R3', page: 4, text: 'GA prints QR + GA Verify per flow', route: '#/registration' },
      { id: 'R4', page: 4, text: 'Supervisor or holding organization approves the record entry', route: '#/registration' },
      { id: 'R5', page: 4, text: 'No SAP registration; store in the WeCGA database', route: '#/registration' },
    ]},
    { group: 'Transfer process (p.5)', items: [
      { id: 'T1', page: 5, text: 'Service request to report transfer / receipt in WeCGA', route: '#/movement' },
      { id: 'T2', page: 5, text: 'Approval request to transferor-side authority', route: '#/movement' },
      { id: 'T3', page: 5, text: 'Approval request to receiver-side authority', route: '#/movement' },
      { id: 'T4', page: 5, text: 'Receiver accepts by scanning QR or pressing accept', route: '#/movement' },
      { id: 'T5', page: 5, text: 'Print paper record; GA Verify; update SAP; export Excel', route: '#/movement' },
      { id: 'T6', page: 2, text: 'Notify moving / logistics team when transferring asset', route: '#/movement' },
    ]},
    { group: 'Loss (p.6)', items: [
      { id: 'L1', page: 6, text: 'Service request to report loss; user writes explanation memo, approval up the line to Head-of', route: '#/writeoff' },
      { id: 'L2', page: 6, text: 'Asset Team checks cause, COST, NBV, compensate or not; attach compensation receipt; Accounting issues receipt', route: '#/writeoff' },
      { id: 'L3', page: 6, text: 'Theft: police daily-record copy attached; company asset needs POA + authorized signatory card', route: '#/writeoff' },
      { id: 'L4', page: 6, text: 'Unknown cause: resignation (supervisor/transferee memo) or disaster (fire/flood/earthquake)', route: '#/writeoff' },
      { id: 'L5', page: 6, text: 'Keep a searchable log in WeCGA', route: '#/audit' },
    ]},
    { group: 'Write-off: sale (p.7)', items: [
      { id: 'WS1', page: 7, text: 'Damaged / not needed asset; insurance claim if any; claimed asset may keep being used (transfer while awaiting) or be sold', route: '#/writeoff' },
      { id: 'WS2', page: 7, text: 'User supervisor approval; open write-off service request; scan+photo; WeCGA generates E-memo detail; attach approved memo', route: '#/writeoff' },
      { id: 'WS3', page: 7, text: 'Asset Team verify: cause, COST, NBV, current storage location', route: '#/writeoff' },
      { id: 'WS4', page: 7, text: 'Sub-committee then Committee approval', route: '#/writeoff' },
      { id: 'WS5', page: 7, text: 'Vendor pays, receipt attached, vendor collects asset', route: '#/writeoff' },
      { id: 'WS6', page: 7, text: 'Remove from SAP; remove from WeCGA if no SAP code; PDF report with run number; GA Verify; SAP update; Excel export; E-memo to stakeholders', route: '#/writeoff' },
    ]},
    { group: 'Write-off: donation (p.8)', items: [
      { id: 'WD1', page: 8, text: 'Unused asset; user opens donation service request (follow scan+photo steps)', route: '#/writeoff' },
      { id: 'WD2', page: 8, text: 'Asset Team check COST/NBV/storage; Sub-committee then Committee', route: '#/writeoff' },
      { id: 'WD3', page: 8, text: 'Recipient receives, issues certificate of appreciation; remove from SAP & WeCGA', route: '#/writeoff' },
    ]},
    { group: 'Write-off: lost (p.9)', items: [
      { id: 'WL1', page: 9, text: 'Service request + memo + line approval; Asset Team check cause/COST/NBV/compensate', route: '#/writeoff' },
      { id: 'WL2', page: 9, text: 'Sub-committee then Committee; compensate; receipts; remove from SAP & WeCGA', route: '#/writeoff' },
    ]},
    { group: 'Count roles & rights (p.10)', items: [
      { id: 'C1', page: 10, text: 'Asset HQ = system admin nationwide', route: '#/admin' },
      { id: 'C2', page: 10, text: 'GA (RO) = regional admin: sees all assets nationwide but can transfer only within own area', route: '#/admin' },
      { id: 'C3', page: 10, text: 'Committee = MASS scan without photo, rights time-bound', route: '#/my-count' },
      { id: 'C4', page: 10, text: 'IT = MASS scan without photo', route: '#/my-count' },
      { id: 'C5', page: 10, text: 'Engineering = MASS scan without photo, only technician equipment', route: '#/my-count' },
      { id: 'C6', page: 10, text: 'All employees = must scan AND photo', route: '#/my-count' },
      { id: 'C7', page: 10, text: 'Count on behalf of others: counter recorded, Owner unchanged; wrong holder -> change-holder service request', route: '#/my-count' },
    ]},
    { group: 'Count types & process (p.10)', items: [
      { id: 'CT1', page: 10, text: 'Annual count done simultaneously nationwide', route: '#/counts' },
      { id: 'CT2', page: 10, text: 'Ad-hoc count scoped by location / asset type / holder (person or org)', route: '#/counts' },
      { id: 'CP1', page: 10, text: '3.1 Create count plan (annual / ad-hoc)', route: '#/counts' },
      { id: 'CP2', page: 10, text: '3.2 User sees what they must count', route: '#/my-count' },
      { id: 'CP3', page: 10, text: '3.3 User can count items in their area even if not the owner', route: '#/my-count' },
      { id: 'CO1', page: 10, text: '3.4 Outcome: found - location & owner correct', route: '#/my-count' },
      { id: 'CO2', page: 10, text: '3.4 Outcome: found - location/owner wrong -> record -> GA Verify -> Transfer', route: '#/my-count' },
      { id: 'CO3', page: 10, text: '3.4 Outcome: found - not in SAP -> Registration', route: '#/my-count' },
      { id: 'CO4', page: 10, text: '3.4 Outcome: found - damaged -> Write-off (damage)', route: '#/my-count' },
      { id: 'CO5', page: 10, text: '3.4 Outcome: not found - lost -> compensation + Write-off lost', route: '#/my-count' },
      { id: 'CO6', page: 10, text: '3.4 Outcome: moved elsewhere -> require note; return to Store/Engineering/Vendor/IT with evidence, else lost; IT names other holder -> change-holder service request', route: '#/my-count' },
      { id: 'CO7', page: 10, text: '3.4 Moved with evidence: open Return service request to Store / Engineering / Vendor / IT to confirm return evidence', route: '#/my-count' },
    ]},
    { group: 'SAP data & reporting (p.11)', items: [
      { id: 'D1', page: 11, text: 'All 33 SAP fields present (Company, Asset Class, Municipality/ECC6.0 No., Asset, Cap.Date, Cost, Accum, NBV, Location, Eva4, Ev.Grp5, Vendor, Useful Life, Warranty ...)', route: '#/assets' },
      { id: 'D4', page: 1, text: 'Install location = SAP Location OR employee org location for movable equipment', route: '#/assets' },
      { id: 'D2', page: 11, text: 'Report shows Found / Not found status and count date', route: '#/reports' },
      { id: 'D3', page: 11, text: 'Log activity shown as a timeline', route: '#/audit' },
    ]},
  ];

  // routes explicitly flagged as carrying open questions to confirm with the customer
  App.OPEN_QUESTIONS = [
    { page: 7, text: 'Can WeCGA route the write-off request to the line supervisor for approval, or must the approved memo come from outside WeCGA? Both paths shown.', route: '#/writeoff' },
    { page: 3, text: 'AI serial-match and fake-photo detection: mocked in the prototype, pending a vendor/model decision.', route: '#/scan' },
  ];

  App.coverageSelfCheck = () => {
    const routes = new Set(App._views.map(v => v.route.split('/').slice(0, 2).join('/')));
    let total = 0, covered = 0; const gaps = [];
    App.COVERAGE.forEach(g => g.items.forEach(it => {
      total++;
      const base = it.route.split('/').slice(0, 2).join('/');
      if (routes.has(base)) covered++; else gaps.push(it.id + ' -> ' + it.route);
    }));
    return { total, covered, gaps };
  };
})();
