/* QR Tagging (#/tagging) + Tagging ticket detail (#/tagging/:id)
   Covers: I5 (Accounting notifies Asset Team), I6 (QR generated by CENTRAL Asset Team only),
           I7 (GA/RO is the controlling intermediary per area),
           I8 (tag applied by GA-Asset Team per area or by local employee/user).
   Partly M3 (Asset Assignment: QR tag per company). */
(function () {
  const App = window.App, ui = App.ui;

  let assignMode = 'area'; // 'area' | 'user'

  const HQ_ONLY = 'QR generation is restricted to the central Asset Team (p.2 5.1)';

  function untagged() {
    return App.store.assets.filter(a => a.tagStatus === 'Not tagged' && a.companyCode === App.session.company);
  }
  function taggingTickets() {
    return App.store.tickets.filter(t => t.type === 'Tagging' && t.company === App.session.company);
  }

  /* Generate QR dialog - only reachable when the button is enabled (asset_hq). */
  function openQrDialog(asset) {
    const comp = App.COMPANIES[App.session.company];
    ui.dialog({
      title: 'Generate QR - ' + App.assetCode(asset),
      sub: `Company-specific tag. ${App.esc(comp)}. QR generated by the central Asset Team only (p.2 5.1, I6).`,
      body: `<div style="display:flex;gap:20px;align-items:center;flex-wrap:wrap">
          ${ui.qr(App.assetCode(asset))}
          <div class="kv" style="grid-template-columns:auto 1fr">
            <dt>Asset</dt><dd>${App.esc([asset.desc1, asset.desc2].filter(Boolean).join(' '))}</dd>
            <dt>Company</dt><dd>${App.esc(comp)}</dd>
            <dt>Serial</dt><dd class="mono">${App.esc(asset.serial || '-')}</dd>
            <dt>Owner</dt><dd>${App.ownerLabel(asset)}</dd>
          </div>
        </div>
        ${ui.callout('info', `The QR encodes the company-specific asset code. Print and hand to GA (RO) for controlled tagging in the area.`)}`,
      actions: [
        { label: 'Print QR sheet', kind: 'tonal', close: false, act: () => window.print() },
        { label: 'Mark QR generated', kind: 'btn', act: () => {
            App.audit({ action: 'QR generated', target: asset.id, detail: 'Company ' + App.session.company });
            ui.toast('QR generated for ' + App.assetCode(asset), 'qr_code_2');
          } },
        { label: 'Close', kind: 'text' },
      ],
    });
  }

  App.registerView('#/tagging', {
    title: 'QR Tagging',
    render() {
      const isHQ = App.hasRole('asset_hq');
      const rows = untagged();
      const areas = App.store.areas.filter(a => a.company === App.session.company);
      const users = App.store.users.filter(u => u.company === App.session.company && (u.role === 'employee' || u.role === 'ga'));

      const kpis = `<div class="grid cols-4">
        ${ui.kpi({ label: 'Awaiting QR / tagging', value: rows.length, icon: 'qr_code_2', tone: 'warn' })}
        ${ui.kpi({ label: 'Open tagging tickets', value: taggingTickets().filter(t => t.status !== 'Completed').length, icon: 'confirmation_number' })}
        ${ui.kpi({ label: 'GA areas (this company)', value: areas.length, icon: 'map', foot: App.session.company === 'AIS' ? 'AIS = 6 areas' : 'BB = 10 areas' })}
        ${ui.kpi({ label: 'QR authority', value: isHQ ? 'Central' : 'Read-only', icon: 'verified_user', tone: isHQ ? 'ok' : 'danger' })}
      </div>`;

      const notifyCallout = ui.callout('info', `p.2 item 5 (I5): <b>Accounting notifies the Asset Team</b> of each new asset so QR tagging can be tracked. This worklist is that queue.`);

      const restrictCallout = isHQ
        ? ui.callout('info', `You are the <b>central Asset Team</b> - QR generation is enabled (p.2 5.1, I6).`)
        : ui.callout('warn', HQ_ONLY + '. Switch role to <b>Asset Team HQ (Central)</b> to generate QR codes.');

      const worklist = ui.card({
        title: `${App.icon('qr_code_2')} Tagging worklist`,
        sub: 'Assets with <b>Not tagged</b> status for this company. QR generation restricted to the central Asset Team (I6).',
        body: ui.table({
          columns: [
            { key: 'code', label: 'Asset code', render: r => `<span class="mono">${App.esc(App.assetCode(r))}</span>` },
            { key: 'desc1', label: 'Description', cls: 'wrap', render: r => App.esc([r.desc1, r.desc2].filter(Boolean).join(' ')) },
            { key: 'area', label: 'Area', render: r => App.esc(r.area || '-') },
            { key: 'owner', label: 'Owner', render: r => App.ownerLabel(r) },
            { key: '_act', label: '', render: r => `<button class="btn sm ${isHQ ? '' : 'outline'}" data-act="qr" data-id="${r.id}" ${isHQ ? '' : 'disabled title="' + HQ_ONLY + '"'}>${App.icon('qr_code_2')} Generate QR</button>` },
          ],
          rows,
          empty: 'Nothing awaiting tagging for this company',
        }),
      });

      const ticketRows = taggingTickets();
      const tickets = ui.card({
        title: `${App.icon('confirmation_number')} Tagging tickets`,
        sub: 'Track the first-record tagging flow. Open a ticket to advance the process.',
        body: ui.table({
          columns: [
            { key: 'id', label: 'Ticket', render: r => `<span class="mono">${r.id}</span>` },
            { key: 'title', label: 'Title', cls: 'wrap' },
            { key: 'assetId', label: 'Asset', render: r => { const a = App.asset(r.assetId); return a ? `<span class="mono">${App.esc(App.assetCode(a))}</span>` : App.esc(r.assetId); } },
            { key: 'status', label: 'Status', render: r => ui.statusChip(r.status) },
          ],
          rows: ticketRows,
          rowLink: r => '#/tagging/' + r.id,
          empty: 'No tagging tickets',
        }),
      });

      // I7 + I8 assignment control
      const modeSeg = `<div class="segmented" data-seg="assignMode" style="margin-bottom:14px">
        <button data-mode="area" class="${assignMode === 'area' ? 'active' : ''}">${App.icon('groups')} By GA-Asset Team (per area)</button>
        <button data-mode="user" class="${assignMode === 'user' ? 'active' : ''}">${App.icon('person')} By local employee / user</button>
      </div>`;

      const modeBody = assignMode === 'area'
        ? ui.callout('info', `p.2 item 7 (I7): <b>GA (RO) is the controlling intermediary</b> for tagging within each area. Tag is applied by the GA-Asset Team (${App.session.company === 'AIS' ? 'AIS = 6 areas' : 'BB = 10 areas'}).`)
          + ui.field({ label: 'Assign to area (GA / RO controlled)', name: 'area', type: 'select', options: areas.map(a => ({ value: a.code, label: a.code + ' - ' + a.name })), hint: 'GA (RO) controls tagging inside the area' })
        : ui.callout('info', `p.2 item 8 (I8): tag applied directly by the <b>local employee / user</b> who holds the asset.`)
          + ui.field({ label: 'Assign to employee / user', name: 'user', type: 'select', options: users.map(u => ({ value: u.id, label: u.name + ' - ' + App.ROLES[u.role] })) });

      const assign = ui.card({
        title: `${App.icon('assignment_turned_in')} Assign tagging`,
        sub: 'p.2 items 7-8 (I7, I8): choose who applies the physical tag.',
        body: modeSeg + `<div class="form-grid">
            ${ui.field({ label: 'Asset to tag', name: 'asset', type: 'select', options: rows.length ? rows.map(a => ({ value: a.id, label: App.assetCode(a) + ' - ' + a.desc1 })) : [{ value: '', label: 'No untagged assets' }] })}
            ${modeBody}
          </div>
          <div class="pill-row" style="margin-top:8px">
            <button class="btn" data-act="assign">${App.icon('send')} Assign &amp; advance ticket</button>
          </div>`,
      });

      return ui.pageHead({
        title: 'QR Tagging',
        sub: 'Generate company-specific QR codes and assign tagging to a GA area or a local user. <span class="muted">p.2 items 5-8 (I5-I8), module M3</span>',
      })
      + kpis + notifyCallout + restrictCallout
      + `<div class="grid cols-2" style="align-items:start"><div>${worklist}${tickets}</div><div>${assign}</div></div>`;
    },
    mount(root) {
      const isHQ = App.hasRole('asset_hq');

      root.querySelectorAll('[data-act="qr"]').forEach(b => b.onclick = () => {
        if (!isHQ) { ui.toast(HQ_ONLY, 'lock'); return; }
        const a = App.asset(b.getAttribute('data-id'));
        if (a) openQrDialog(a);
      });

      root.querySelectorAll('[data-seg="assignMode"] [data-mode]').forEach(b => b.onclick = () => {
        assignMode = b.getAttribute('data-mode'); App.refresh();
      });

      const assign = root.querySelector('[data-act="assign"]');
      if (assign) assign.onclick = () => {
        const assetId = root.querySelector('[name="asset"]').value;
        const asset = App.asset(assetId);
        if (!asset) { ui.toast('No asset selected to tag', 'error'); return; }
        let target, note;
        if (assignMode === 'area') {
          const area = root.querySelector('[name="area"]').value;
          target = 'Area ' + area + ' (GA/RO controlled)';
          note = 'Tag applied by GA-Asset Team in area ' + area + ' (GA/RO intermediary)';
        } else {
          const u = App.user(root.querySelector('[name="user"]').value);
          target = u ? u.name : 'local user';
          note = 'Tag applied by local employee/user: ' + target;
        }
        // Advance an existing tagging ticket for this asset, or create one.
        let t = App.store.tickets.find(x => x.type === 'Tagging' && x.assetId === assetId);
        if (t) {
          App.advanceTicket(t, note);
        } else {
          t = App.addTicket({ type: 'Tagging', flow: 'tagging', title: 'Tagging - ' + App.assetTitle(asset), assetId, status: 'In progress', area: asset.area });
          t.history.push({ ts: new Date().toISOString(), actor: App.currentUser().name, step: 'Assigned', note });
        }
        App.audit({ action: 'Tagging assigned', target: t.id, detail: note });
        ui.toast('Tagging assigned - ' + target, 'assignment_turned_in');
        App.refresh();
      };
    },
  });

  // ---------- Tagging ticket detail ----------
  App.registerView('#/tagging/:id', {
    title: ctx => ctx.params.id,
    render(ctx) {
      const t = App.ticket(ctx.params.id);
      if (!t) return ui.pageHead({ title: 'Ticket not found', breadcrumb: [{ label: 'QR Tagging', hash: '#/tagging' }, { label: ctx.params.id }] });
      const a = App.asset(t.assetId);
      const flow = App.FLOWS[t.flow] || App.FLOWS.tagging;
      const isFinal = t.stepIndex >= flow.length - 1;

      const summary = a ? ui.card({
        title: `${App.icon('inventory_2')} Asset`,
        actions: `<button class="btn text sm" data-nav="#/assets/${a.id}">Open asset</button>`,
        body: `<div class="kv" style="grid-template-columns:auto 1fr">
            <dt>Code</dt><dd class="mono">${App.esc(App.assetCode(a))}</dd>
            <dt>Description</dt><dd>${App.esc([a.desc1, a.desc2].filter(Boolean).join(' '))}</dd>
            <dt>Serial</dt><dd class="mono">${App.esc(a.serial || '-')}</dd>
            <dt>Area</dt><dd>${App.esc(a.area || '-')}</dd>
            <dt>Owner</dt><dd>${App.ownerLabel(a)}</dd>
            <dt>Tag status</dt><dd>${ui.statusChip(a.tagStatus)}</dd>
          </div>` }) : ui.callout('warn', 'Asset not found for this ticket.');

      const stepper = ui.card({
        title: `${App.icon('checklist')} Tagging flow`,
        sub: 'p.2 items 5-8 - the exact process steps (I5-I8). Advance to walk the customer through each stage.',
        body: ui.stepper(flow, t.stepIndex)
          + `<div class="pill-row" style="margin-top:14px">
              ${isFinal
                ? `<button class="btn tonal" data-nav="#/scan?asset=${t.assetId}">${App.icon('photo_camera')} First record (scan + photos)</button>`
                : `<button class="btn" data-act="advance">${App.icon('arrow_forward')} Advance step</button>`}
              ${t.assetId ? `<button class="btn text" data-nav="#/scan?asset=${t.assetId}">Go to Scan &amp; Record</button>` : ''}
            </div>`,
      });

      const history = ui.card({
        title: `${App.icon('history')} History`,
        body: (t.history && t.history.length)
          ? ui.timeline(t.history.map(h => ({ title: h.step, meta: `${App.fmt.datetime(h.ts)} - ${h.actor}${h.note ? ' - ' + h.note : ''}` })))
          : '<div class="muted">No steps recorded yet.</div>',
      });

      return ui.pageHead({
        title: t.id + ' - ' + t.title,
        breadcrumb: [{ label: 'QR Tagging', hash: '#/tagging' }, { label: t.id }],
        sub: `${ui.statusChip(t.status)} &nbsp; Company ${App.esc(App.COMPANIES[t.company] || t.company)} &nbsp; Area ${App.esc(t.area || '-')}`,
      })
      + `<div class="grid cols-2" style="align-items:start"><div>${stepper}${history}</div><div>${summary}</div></div>`;
    },
    mount(root, ctx) {
      const adv = root.querySelector('[data-act="advance"]');
      if (adv) adv.onclick = () => {
        const t = App.ticket(ctx.params.id);
        App.advanceTicket(t);
        ui.toast('Step advanced', 'arrow_forward');
        App.refresh();
      };
    },
  });
})();
